"""Add Drill and DrillCategory tables

Revision ID: 2d9eb6deeb04
Revises: 3be1661b988d
Create Date: 2025-11-07 10:21:57.672144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9eb6deeb04'
down_revision: Union[str, Sequence[str], None] = '3be1661b988d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
