"""Add planned_drill_ids to team_events table

Revision ID: 7defcd3042a0
Revises: 2d9eb6deeb04
Create Date: 2025-11-07 18:20:06.906026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7defcd3042a0'
down_revision: Union[str, Sequence[str], None] = '2d9eb6deeb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_events', sa.Column('planned_drill_ids', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_events', 'planned_drill_ids')
    # ### end Alembic commands ###
