"""Add status column to TeamEvent

Revision ID: 92dc7c19b42d
Revises: 
Create Date: 2025-11-06 21:55:37.817195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dc7c19b42d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_events', sa.Column('status', sa.Enum('PLANNED', 'CANCELED', 'COMPLETED', name='eventstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_events', 'status')
    # ### end Alembic commands ###
