"""Add wellness and injury tables for Phase 11

Revision ID: a636ebce9417
Revises: 7defcd3042a0
Create Date: 2025-11-07 21:37:49.834791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a636ebce9417'
down_revision: Union[str, Sequence[str], None] = '7defcd3042a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
