"""Add Drill and DrillCategory tables

Revision ID: f81a1a399111
Revises: 28b36563c1f4
Create Date: 2025-11-07 09:44:32.220574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81a1a399111'
down_revision: Union[str, Sequence[str], None] = '28b36563c1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drill_categories_id'), 'drill_categories', ['id'], unique=False)
    op.create_index(op.f('ix_drill_categories_name'), 'drill_categories', ['name'], unique=False)
    op.create_table('drills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['drill_categories.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drills_id'), 'drills', ['id'], unique=False)
    op.create_index(op.f('ix_drills_title'), 'drills', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drills_title'), table_name='drills')
    op.drop_index(op.f('ix_drills_id'), table_name='drills')
    op.drop_table('drills')
    op.drop_index(op.f('ix_drill_categories_name'), table_name='drill_categories')
    op.drop_index(op.f('ix_drill_categories_id'), table_name='drill_categories')
    op.drop_table('drill_categories')
    # ### end Alembic commands ###
